package plataforma;

import java.util.Scanner;

/**
 *
 * @author DANIELCASTELAO\mmartinezcosta
 */
public class Principal extends javax.swing.JFrame {

     
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    this.setResizable(false);
    this.setSize(1280,720);
    this.setLocationRelativeTo(null);
    
        Carne.setVisible(false);
        Pescado.setVisible(false);
        Ensalada.setVisible(false);
        Seleccion.setVisible(false);
    
    
    }
    
    public void Pedido() {
                
        ComerAquí.setEnabled(true);
        ParaLlevar.setEnabled(true);
        Carne.setEnabled(true);
        Pescado.setEnabled(true);
        Ensalada.setEnabled(true);
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ParaLlevar = new javax.swing.JButton();
        ComerAquí = new javax.swing.JButton();
        Carne = new javax.swing.JButton();
        Pescado = new javax.swing.JButton();
        Ensalada = new javax.swing.JButton();
        Seleccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(187, 127, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ParaLlevar.setText("ParaLlevar");
        jPanel1.add(ParaLlevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, -1, -1));

        ComerAquí.setText("ComerAquí");
        ComerAquí.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComerAquíActionPerformed(evt);
            }
        });
        jPanel1.add(ComerAquí, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        Carne.setText("Carne");
        jPanel1.add(Carne, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        Pescado.setText("Pescado");
        jPanel1.add(Pescado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, -1, -1));

        Ensalada.setText("Ensalada");
        jPanel1.add(Ensalada, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, -1, -1));

        Seleccion.setText("Seleccione su plato");
        jPanel1.add(Seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComerAquíActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComerAquíActionPerformed
        // TODO add your handling code here:
                       
        Scanner sc=new Scanner(System.in);
        int comensales;
        System.out.println("Cuantos comensales:");
        comensales=sc.nextInt();
        
            if (comensales!=0){
                
            Seleccion.setVisible(true);
            
            Carne.setVisible(true);
            Pescado.setVisible(true);
            Ensalada.setVisible(true);
            
            Carne.setEnabled(true);
            Pescado.setEnabled(true);
            Ensalada.setEnabled(true);
               
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ComerAquíActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carne;
    private javax.swing.JButton ComerAquí;
    private javax.swing.JButton Ensalada;
    private javax.swing.JButton ParaLlevar;
    private javax.swing.JButton Pescado;
    private javax.swing.JLabel Seleccion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
